---
title: "[cars](https://github.com/kelly-sovacool/cars/)"
date: today
format:
  html:
    code-fold: true
params:
  interactive: false
engine: knitr
execute:
  message: false
dpi: 300
---

View interactive shiny app for general case: 
<https://kelly-sovacool.shinyapps.io/car-costs/>

```{r setup}
library(googlesheets4)
library(glue)
library(here)
library(magrittr)
library(scales)
library(tidyverse)
theme_set(theme_bw())
```

```{r data_gs4, eval=params$interactive}
gs4_auth()
cars <- read_sheet(
    'https://docs.google.com/spreadsheets/d/1uFAE4Ss_Yy6Ybp90YGXgQJfhAOiut1pyVKBmqc570F0'
) %>% mutate(make = as.character(make))
cars %>% write_csv(here('data','cars.csv'))
```
```{r data_load, eval=!params$interactive}
cars <- read_csv(here('data','cars.csv'))
```

```{r calc_costs}
ev_incentive <- 7500
energy_price_per_kwh <- 0.25 # TODO look up our actual rate in electricity bill
gas_price_per_gal <- 3 # TODO find gas price predictions

dav_commute <- 30 * 4 # mileage + trips per week
kel_a2_trips <- 55.4 / 2 # A2 roundtrip once every two week
road_trips_year <- 532 * 1 + # indy
    408 * 1 + # columbus
    580 * 1 # des plaines
mileage_per_week <- dav_commute + kel_a2_trips + road_trips_year/52

cars %<>% mutate(
    price_minus_incentives = case_when(
        type == 'EV' ~ price_approx - ev_incentive,
        type == 'plug-in hybrid' ~ price_approx - ev_incentive /
            2,
        TRUE ~ price_approx
    ),
    cost_per_mile = case_when(
        str_detect(type, 'EV') ~ battery_kWh * energy_price_per_kwh / range_mi,
        str_detect(type, 'ICE') ~ gas_price_per_gal / mpg_combined
    ),
    make_model = glue("{make} {model}"),
    purchase_cost = price_minus_incentives
) %>% 
    filter(!is.na(battery_kWh | !is.na(mpg_combined)),
           make_model != 'Saturn Vue'
           )

n_years <- 8
start_date <- ymd('2025-09-30')
time_dat <- start_date + weeks(1:(52 * n_years))

car_cost_over_time <- time_dat %>% 
    lapply(\(date_week) {
        cars %>% 
            mutate(date_week = date_week,
                   cost_per_week = mileage_per_week * cost_per_mile)
    }) %>% 
    bind_rows() %>% 
    group_by(make_model) %>% 
    mutate(total_cost = cumsum(cost_per_week) + purchase_cost)
```

## Car cost over time

```{r plot_cost_time}
vehicles <- car_cost_over_time %>% 
    slice_max(date_week) %>% 
    arrange(desc(total_cost)) %>% 
    pull(make_model)
car_cost_over_time %>% 
    mutate(make_model = factor(make_model, levels = vehicles)) %>% 
    ggplot(aes(date_week, total_cost, color = make_model, group = make_model)) +
    geom_line() +
    scale_color_brewer(palette = 'Dark2') +
    #scale_color_viridis_d(option = 'viridis') +
    scale_y_continuous(labels = label_currency()) +
    guides(color = guide_legend(title = 'vehicle')) +
    labs(x = '',
         y = 'Total Cost')
```

## Car cost over miles driven

```{r plot_cost_miles}
car_cost_over_miles <- seq(from = 0, to = 100000, by = 10000) %>% 
    lapply(\(miles) {
        cars %>% 
            mutate(miles=miles,
                   cost_at_mileage = purchase_cost + miles * cost_per_mile)
    }) %>% 
    bind_rows()
car_cost_over_miles %>% 
    mutate(make_model = factor(make_model, levels = vehicles)) %>% 
    ggplot(aes(miles, cost_at_mileage, color = make_model, group = make_model)) +
    geom_line() +
    scale_color_brewer(palette = 'Dark2') +
    #scale_color_viridis_d(option = 'viridis') +
    scale_y_continuous(labels = label_currency()) +
    guides(color = guide_legend(title = 'vehicle')) +
    labs(x = '',
         y = 'Total Cost')
```


