name: quarto

on:
    workflow_dispatch:
    push:
      branches:
        - main

permissions:
  contents: write
  pages: write

jobs:
    deploy-quarto:
      runs-on: macos-latest

      steps:
        - uses: actions/checkout@v4
        - uses: r-lib/actions/setup-r@v2
        - uses: r-lib/actions/setup-r-dependencies@v2

        - name: Publish to GitHub Pages (and render)
          uses: quarto-dev/quarto-actions/publish@v2
          with:
            target: gh-pages
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
