name: shiny

on:
    workflow_dispatch:
    push:
      branches:
        - main

jobs:
    deploy-shiny:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: r-lib/actions/setup-r@v2
        - uses: r-lib/actions/setup-r-dependencies@v2
        - uses: quarto-dev/quarto-actions/render@v2
          with:
            path: app.qmd
        - name: deploy shiny app
          shell: Rscript {0}
          run: |
            rsconnect::setAccountInfo(name='kelly-sovacool',
                                      token='${{ secrets.SHINYAPPS_TOKEN }}',
                                      secret='${{ secrets.SHINYAPPS_SECRET }}')
            rsconnect::deployApp(appPrimaryDoc = 'app.qmd', appName = 'car-costs', forceUpdate = TRUE)
